version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: task_manager
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRES_IN: 3600s
      UPLOAD_PATH: ./uploads
    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:3000/api
      VITE_APP_NAME: Task Manager
    depends_on:
      - backend

volumes:
  postgres_data: